### PR TITLE
Feature/shared resoruces

### PR DESCRIPTION
**Pull request by rebeccaRossRobotics**
<ins>Background</ins>
When dealing with really big behaviour trees in the past we have found that the loading and execution becomes quite slow. (More details can be found in this [issue](https://github.com/BehaviorTree/BehaviorTree.CPP/issues/550))

In that issue it was suggested taking a singleton approach so that only one instance was created per different service/action/publisher call. At the time we were still using bt v3.8 so implemented a solution locally. We are at the stage where we want to upgrade to bt v4.0 and use this library. When looking at the code I noticed that this is a concept that had been implemented in the RosTopicSubNode but not in the RosActionNode, RosServiceNode and RosTopicPubNode. 

<ins>PR contents</ins>
I have implemented a similar approach to the RosTopicSubNode for the RosActionNode, RosServiceNode and RosTopicPubNode. Making it so that if any ros interface (publisher,subscriber,service client or action client) is called from multiple places in a tree it will use the same instance.

I also created a service server (simple adding two ints together) and examples to test the service client and publisher.

I hoping that you find this functionality useful and others will benefit. More than happy for suggestions if there is a better way to implement this functionality. 

<ins>To test</ins>
To test and prove this i placed a log which displays the hex value of the pointer. And in the tree had 2 instances of the same class, the pointer should match. And then if you had 2 instances of a publisher (for example) but different topic_names then two instances of the base class would be made and the log would show a different pointer.
`RCLCPP_INFO(rclcpp::get_logger("test"), "%s, publisher pointer: %p", name().c_str(), reinterpret_cast<void*>(pub_instance_->publisher_.get()));`

I look forward to your feedback :)

### CODE REVIEW

**Comment by facontidavide** [comment]
Thanks. I will look into this soon and come back to you.

**Comment by rebeccaRossRobotics** [comment]
Hi @facontidavide Have you had a chance to give this a look?

**Comment by facontidavide** [comment]
Hi

I started porting this manually. Can you check  this commit and see if I have forgotten anything? 

https://github.com/BehaviorTree/BehaviorTree.ROS2/commit/3b399da8b29b117b36fd283f8784f6b0ff54a14a

**Comment by facontidavide** [comment]
also, you will notice that the registry uses **weak_ptr** now, that makes the auto-destruction much easier (I wonder how I didn't realize that earlier).

**Comment by rebeccaRossRobotics** [comment]
Ok, i'll have a look over the next few days and let you know!

**Pull request closed without merging**
